heraldic/rendering/flask/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
This module implements form classes based on FlaskForm.
"""

from flask_wtf import FlaskForm, Form
from wtforms.fields import *
from heraldic.models.document_model import DocumentModel
from heraldic.models.attribute import *
from wtforms.validators import ValidationError


class UrlForm(FlaskForm):
    url = StringField("URL de l'article")
    gather_again = HiddenField()

    submit = SubmitField(u'Soumettre')


class ReviewForm(FlaskForm):
    @classmethod
    def apply_model(cls, model: DocumentModel):
        for k, v in model.attributes.items():
            if not v.displayable:
                continue
            field_class = Attribute
            kwargs = {'label': v.desc}
            if k == 'id':
                field_class = HiddenField
            elif isinstance(v, KeywordAttribute) or isinstance(v, DateAttribute) or isinstance(v, TextAttribute):
                field_class = StringField
            elif isinstance(v, KeywordListAttribute):
                field_class = TextAreaField
            elif isinstance(v, BooleanAttribute):
                field_class = SelectField
                kwargs['choices'] = [('', ''), ('yes', 'Oui'), ('no', 'Non')]

                # Add default parameter first for handling WTForms issue #289
                kwargs['default'] = ''

            if not v.revisable and k != 'id':
                kwargs['render_kw'] = {'disabled': 'disabled'}
            if v.revisable:
                kwargs['validators'] = [cls.generate_validator(v)]
            setattr(cls, k, field_class(**kwargs))

        setattr(cls, 'submit', SubmitField('Corriger'))
        setattr(cls, 'gather_again', SubmitField('Récupérer à nouveau'))

    def apply_model_default_values(self, model: DocumentModel):
        for k, v in model.attributes.items():
            if not v.displayable:
                continue
            if v.parsing_error:
                getattr(self, k).label.text = v.desc + ' (' + v.parsing_error + ')'
            else:
                getattr(self, k).default = v.render_for_display()

    @classmethod
    def generate_validator(cls, attribute):
        def validator(form, field):
            if not attribute.validate(field.data):
                raise ValidationError(attribute.validate_failure_text)

        return validator


class DisplayDocumentForm(FlaskForm):
    id = HiddenField()

    submit = SubmitField(u'Mettre à jour l\'article')

heraldic/rendering/flask/blueprints/blueprints.py
# -*- coding: utf-8 -*-
"""

"""

from flask import Blueprint, request, render_template, flash, redirect, url_for, abort
from flask_nav.elements import Navbar, View

from heraldic.misc.exceptions import DocumentNotChangedException
from heraldic.models.document import Document
from heraldic.rendering.flask.forms import UrlForm, ReviewForm, DisplayDocumentForm
from heraldic.rendering.flask.nav import nav
from heraldic.media.known_media import known_media
from heraldic.store import index_searcher


bp = Blueprint('heraldicapp', __name__)

nav.register_element('heraldic_top', Navbar(
    View('Liste', '.home'),
    View('Soumettre un article', '.submit_document')
))


@bp.route("/", methods=['GET'])
def home():
    media_classes = known_media.media_classes
    return render_template('home.html', media_classes=media_classes)


@bp.route('/display_media', methods=['GET'])
def display_media():
    media_id = request.args.get('media_id')
    if not known_media.media_exists(media_id):
        abort(401)
    hits_generator = index_searcher.search_by_media(media_id)
    hits_models = [next(hits_generator) for _ in range(100)]
    return render_template('search.html', hits=hits_models)


@bp.route('/display_document', methods=['GET', 'POST'])
def display_document():
    doc_id = request.args.get('doc_id')

    d = Document(doc_id=doc_id)
    d.retrieve_old_versions()

    form = DisplayDocumentForm(data={'id': d.model.id.value})

    return render_template('display_document.html', document=d, form=form)


@bp.route('/submit_document', methods=['GET', 'POST'])
def submit_document():
    form = UrlForm()

    if form.validate_on_submit():
        url = form.url.data

        d = Document(url)
        if d.model.initialized:
            flash("L'article existe déjà", "warning")
        else:
            d.gather()
            flash("L'article a été récupéré", "info")

        return redirect(url_for('heraldicapp.review_document', id=d.model.id))

    return render_template('url_form.html', form=form)


@bp.route("/review_document", methods=['GET', 'POST'])
def review_document():
    doc_id = request.form['id'] if request.method == 'POST' else request.args['id']
    d = Document(doc_id=doc_id)

    ReviewForm.apply_model(d.model)
    form = ReviewForm()

    if form.validate_on_submit():
        if 'gather_again' in request.form:
            try:
                d.gather(update_inplace=True)
                flash("L'article a de nouveau été récupéré", "info")
            except DocumentNotChangedException:
                flash("Aucune mise à jour constatée", "danger")
        else:
            try:
                d.update_from_revision(request.form)
                flash("L'article a été mis à jour", "info")
            except DocumentNotChangedException:
                flash("Aucune mise à jour constatée", "danger")

    form.apply_model_default_values(d.model)

    form.process()
    return render_template('review_document.html', form=form)


@bp.route("/regather_document", methods=['GET'])
def regather_document():
    doc_id = request.args['id']
    d = Document(doc_id=doc_id)
    try:
        d.gather(update_inplace=True)
    except DocumentNotChangedException:
        flash("Aucune mise à jour constatée", "danger")
    d.retrieve_old_versions()

    form = DisplayDocumentForm(data={'id': d.model.id.value})

    return render_template('display_document.html', document=d, form=form)

heraldic/rendering/flask/templates/display_document.html
{% extends "layout.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}

{% for k, v in document.model.attributes.items() if v.displayable %}
<div class="row">
  <div class="col-sm-2"><a data-toggle="collapse" data-target="#{{k}}-old-versions">{{v.desc}}</a></div>
  <div class="col-sm-1">{{v.version_no}}</div>
  <div class="col-sm-9">{{v.render_for_display()}}</div>
    <div id="{{k}}-old-versions" class="collapse col-sm-10 col-sm-offset-2">
    {% for old_model in document.old_versions[::-1] if old_model.attributes[k].initialized %}
        <div class="row">
        <div class="col-sm-1">{{old_model.attributes[k].version_no}}</div>
        <div class="col-sm-9">{{old_model.attributes[k].render_for_display()}}</div>
</div>
    {% endfor %}
        </div>
</div>
{%      endfor %}
    <div class="col-md-12">
       <a href="{{url_for('heraldicapp.review_document', id=document.model.id.value)}}" class="btn btn-info" role="button">Mettre à jour l'article</a>
   </div>
    {%- endblock %}

heraldic/rendering/flask/templates/home.html
{% extends "layout.html" %}
{% block content %}
   <div class="container">
      <div class="jumbotron">
        <h1>Liste des médias</h1>
      </div>
        <div class="list-group">
        {% for media in media_classes %}
          <a href="{{url_for('heraldicapp.display_media')}}?media_id={{media.id}}" class="list-group-item">{{media.display_name}} <span class="badge">{{media.get_document_count()}}</span></a>
          {% endfor %}
        </div>
   </div>
{%- endblock %}

heraldic/rendering/flask/templates/layout.html
{% extends "bootstrap/base.html" %}
{% block title %}Heraldic{% endblock %}

{% block navbar %}
{{nav.heraldic_top.render()}}
{% endblock %}

{% block content %}
  <h1>Hello, Bootstrap</h1>
{% endblock %}

heraldic/rendering/flask/templates/review_document.html
{% import "bootstrap/wtf.html" as wtf %}

{% extends "layout.html" %}
{% block content %}
   <div class="container">
      <div class="jumbotron">
        <h1>Corriger un article</h1>
      </div>
       {% with messages = get_flashed_messages(with_categories=true) %}
  <!-- Categories: success (green), info (blue), warning (yellow), danger (red) -->
  {% if messages %}
    {% for category, message in messages %}
      <div class="alert alert-{{ category }} alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      {{ message }}
      </div>
    {% endfor %}
  {% endif %}
{% endwith %}
   <div class="col-md-12">
       <form action="{{url_for('heraldicapp.review_document')}}" class="form" method="POST">
            {{ form.hidden_tag() }}
            {{ wtf.form_errors(form, hiddens='only') }}

            {%- for field in form %}
            {% if not bootstrap_is_hidden_field(field) -%}

              {{ wtf.form_field(field,
                            form_type='basic',
                            horizontal_columns=('lg', 2, 10),
                            button_map={'submit': 'primary', 'gather_again': 'secondary'}) }}
            {%- endif %}
            {%- endfor %}
       </form>
   </div>
{%- endblock %}

heraldic/rendering/flask/templates/search.html
{% extends "layout.html" %}
{% block content %}
   <div class="container">
      <div class="jumbotron">
        <h1>Liste des articles</h1>
      </div>
        <div class="list-group">
        {% for hit in hits %}
          <a href="{{url_for('heraldicapp.display_document')}}?doc_id={{hit.id.render_for_display()}}" class="list-group-item">{{hit.title.render_for_display()}}</a>
          {% endfor %}
        </div>
   </div>
{%- endblock %}

heraldic/rendering/flask/templates/url_form.html
{% import "bootstrap/wtf.html" as wtf %}

{% extends "layout.html" %}
{% block content %}
   <div class="container">
      <div class="jumbotron">
        <h1>Soumettre un article</h1>
        <p>Entrez une URL</p>
      </div>
   <div class="col-md-12">
       {{wtf.quick_form(form, novalidate=True)}}
   </div>
{%- endblock %}